### ISSUE TITLE
By when do you expect to finish working on this project?

### ISSUE THREAD

**Issue by GalGreenfield** [WP-API/wp-api-customize-endpoints#18]
Do you think that the team might finish working on this by the release date of WordPress's 4.7 release date (November 14, 2017)?

**Comment by westonruter** [comment]
@GalGreenfield Do you mean WordPress 4.9? In any case, no, it won't be done by 4.9 if by done you mean merged into WordPress core. We'll be using these endpoints to serve as the basis of next generation of the Customizer app in a new feature plugin, similar to how Gutenberg is being developed. I expect the feature plugin to be worked on during the 5.0 release cycle while Gutenberg is being merged into core. During the feature plugin development, we'll be able to test and validate that the customize endpoints are feature complete.
